version: "1.0"
services:
  postgres:
    image: postgres:16.2-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5434:5434
    command:
      - "postgres"
      - "-c"
      - "port=5434"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5434 -d postgres -q"]
      interval: 3s
      timeout: 3s
      retries: 5

  app:
    build: .
    env_file:
      - .env
    container_name: app
    ports:
      - 8000:8000
    command: /app/docker/app.sh
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${STORAGE_PATH}:${DOCKER_PATH}