version: "1.0"
services:
  postgres:
    image: postgres:16.2
    container_name: database
    ports:
      - 5433:5433
    environment:
      - POSTGRES_PASSWORD=postgres
    command:
      - "postgres"
      - "-c"
      - "port=5433"