version: "1.0"
services:
  postgres:
    image: postgres:16.2-alpine
    container_name: postgres
    ports:
      - 5434:5434
    environment:
      - POSTGRES_PASSWORD=postgres
    command:
      - "postgres"
      - "-c"
      - "port=5434"